# Generated by Django 4.1.4 on 2022-12-18 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAdmintable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, null=True)),
                ('test', models.DateField(blank=True, null=True)),
                ('test2', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'base_admintable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('role', models.CharField(choices=[('responsable informatique', 'Responsable Informatique'), ('chargee affaire', 'Chargee Affaire'), ('responsable logistique1', 'Responsable Logistique 1'), ('responsable financier', 'Responsable Financier'), ('responsable logistique2', 'Responsable Logistique 2')], max_length=100, null=True)),
                ('etape', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etapes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('numero', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralDTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_Dossier', models.IntegerField(null=True)),
                ('fournisseur', models.CharField(max_length=200, null=True)),
                ('pays', models.CharField(max_length=100, null=True)),
                ('nom', models.CharField(max_length=200, null=True)),
                ('client', models.CharField(max_length=200, null=True)),
                ('date_VCL', models.DateTimeField(null=True)),
                ('date_validation_e1', models.DateTimeField(null=True)),
                ('statut_Imp', models.CharField(choices=[('', ''), ('En Negociation', 'En Négociation'), ('Confirmée fournée', 'Confirmée Fournée'), ('ex_c_payement', 'Ex_C_Payement'), ('En Préparation', 'En Préparation'), ('Prélevée', 'Prélevée'), ('Arrivée Maroc', 'Arrivée Maroc'), ('En Dédouanement', 'En Dédouanement'), ('Liquidée', 'Liquidée'), ('En Entrepôt', 'En Entrepôt'), ('Livrée', 'Livrée'), ('clôturée', 'clôturée')], default='', max_length=20, null=True)),
                ('date_TCS', models.DateTimeField(null=True)),
                ('code_Four_Sage', models.CharField(default='', max_length=200, null=True)),
                ('ref_Bon_Cmd_Sage', models.CharField(default='', max_length=200, null=True)),
                ('cat_Cmd', models.CharField(default='', max_length=200, null=True)),
                ('date_CCF', models.DateTimeField(null=True)),
                ('n_FP', models.CharField(default='', max_length=200, null=True)),
                ('date_FP', models.DateTimeField(null=True)),
                ('pays_Origine', models.CharField(default='', max_length=200, null=True)),
                ('incoterm', models.CharField(default='', max_length=200, null=True)),
                ('pays_Prt', models.CharField(default='', max_length=200, null=True)),
                ('montant_Dev', models.CharField(default='', max_length=200, null=True)),
                ('devise', models.CharField(default='', max_length=200, null=True)),
                ('mode_Pay', models.CharField(default='', max_length=200, null=True)),
                ('delai_Liv', models.CharField(default='', max_length=200, null=True)),
                ('Exec_Co_Pay', models.CharField(default='', max_length=200, null=True)),
                ('date_PPF', models.DateTimeField(null=True)),
                ('date_PAM', models.DateTimeField(null=True)),
                ('date_validation_e2', models.DateTimeField(null=True)),
                ('delai_e2', models.IntegerField(null=True)),
                ('date_pickup', models.DateTimeField(null=True)),
                ('freightforward', models.CharField(default='', max_length=100, null=True)),
                ('mode_trans', models.CharField(default='', max_length=100, null=True)),
                ('date_AM', models.CharField(default='', max_length=100, null=True)),
                ('transitaire', models.CharField(default='', max_length=100, null=True)),
                ('Mt_ded_dh', models.CharField(default='', max_length=100, null=True)),
                ('date_ld', models.DateTimeField(null=True)),
                ('date_lc', models.DateTimeField(null=True)),
                ('litige', models.CharField(default='', max_length=100, null=True)),
                ('class_litige', models.CharField(default='', max_length=100, null=True)),
                ('date_validation_e3', models.DateTimeField(null=True)),
                ('delai_e3', models.IntegerField(null=True)),
                ('date_capf', models.DateTimeField(null=True)),
                ('date_capp', models.DateTimeField(null=True)),
                ('date_validation_e4', models.DateTimeField(null=True)),
                ('delai_e4', models.IntegerField(null=True)),
                ('date_cacrs', models.DateTimeField(null=True)),
                ('date_validation_e5', models.DateTimeField(null=True)),
                ('delai_e5', models.IntegerField(null=True)),
                ('etape', models.IntegerField(default=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['etape'],
            },
        ),
        migrations.CreateModel(
            name='ConTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ', models.CharField(default='', max_length=100, null=True)),
                ('column', models.IntegerField(default=1)),
                ('type', models.CharField(choices=[('VARCHAR', 'Text'), ('DATE', 'Date'), ('BIGINT', 'number')], max_length=100, null=True)),
                ('etape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.etapes')),
            ],
        ),
    ]
