# Generated by Django 4.1.4 on 2023-01-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapes',
            name='date_validation',
            field=models.DateField(null=True),
        ),
    ]
